spring.application.name=spring-boot-store-management-api
server.port=2028

#spring.datasource.url=jdbc:mysql://localhost:3306/cheese_store_db?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/cheese_store_db

spring.datasource.username=root
#DELETE BEFORE PUSHING
spring.datasource.password=almostgotme

# recommended to be removed
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#options: none, create-only, drop, crate, create-drop, validate, update
#tells generate db tables automatically for us
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.indent-output=true

#spring.main.debug=true
logging.level.org.hibernate.tool.hbm2ddl=DEBUG
