spring.application.name=spring-boot-store-managament-api
server.port=2028
spring.datasource.url=jdbc:mysql://localhost:3306/cheese_store_db

#COMMENT BEFORE PUSHING
spring.datasource.username=root
spring.datasource.password=RaccMel.SQL2025

# this is the latest Hibernate dialect for the db
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true;
spring.jpa.properties.hibernate.format_sql=true;

spring.jackson.serialization.indent_output=true

spring.main.debug=true
